# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

host: Optional[str]
"""
ESXi Host Name config
"""

ovfToolDatastoreName: Optional[str]
"""
ESXi Datastore Name config were ovftool will be configured
"""

password: Optional[str]
"""
ESXi Password config
"""

sshPort: str
"""
ESXi Host SSH Port config
"""

sslPort: str
"""
ESXi Host SSL Port config
"""

username: str
"""
ESXi Username config
"""

