// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EsxiNative
{
    [EsxiNativeResourceType("esxi-native:index:PortGroup")]
    public partial class PortGroup : Pulumi.CustomResource
    {
        /// <summary>
        /// Forged transmits (true=Accept/false=Reject).
        /// </summary>
        [Output("forgedTransmits")]
        public Output<bool?> ForgedTransmits { get; private set; } = null!;

        /// <summary>
        /// MAC address changes (true=Accept/false=Reject).
        /// </summary>
        [Output("macChanges")]
        public Output<bool?> MacChanges { get; private set; } = null!;

        /// <summary>
        /// Port Group name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Promiscuous mode (true=Accept/false=Reject).
        /// </summary>
        [Output("promiscuousMode")]
        public Output<bool?> PromiscuousMode { get; private set; } = null!;

        /// <summary>
        /// Virtual Switch Name.
        /// </summary>
        [Output("vSwitch")]
        public Output<string?> VSwitch { get; private set; } = null!;

        /// <summary>
        /// Port Group vlan id
        /// </summary>
        [Output("vlan")]
        public Output<int?> Vlan { get; private set; } = null!;


        /// <summary>
        /// Create a PortGroup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PortGroup(string name, PortGroupArgs? args = null, CustomResourceOptions? options = null)
            : base("esxi-native:index:PortGroup", name, args ?? new PortGroupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PortGroup(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("esxi-native:index:PortGroup", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PortGroup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PortGroup Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PortGroup(name, id, options);
        }
    }

    public sealed class PortGroupArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Forged transmits (true=Accept/false=Reject).
        /// </summary>
        [Input("forgedTransmits")]
        public Input<bool>? ForgedTransmits { get; set; }

        /// <summary>
        /// MAC address changes (true=Accept/false=Reject).
        /// </summary>
        [Input("macChanges")]
        public Input<bool>? MacChanges { get; set; }

        /// <summary>
        /// Virtual Switch name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Promiscuous mode (true=Accept/false=Reject).
        /// </summary>
        [Input("promiscuousMode")]
        public Input<bool>? PromiscuousMode { get; set; }

        /// <summary>
        /// Virtual Switch Name.
        /// </summary>
        [Input("vSwitch")]
        public Input<string>? VSwitch { get; set; }

        /// <summary>
        /// Port Group vlan id
        /// </summary>
        [Input("vlan")]
        public Input<int>? Vlan { get; set; }

        public PortGroupArgs()
        {
        }
    }
}
