// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// ESXi Host Name config
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:host")
}

// ESXi Datastore Name config were ovftool will be configured
func GetOvfToolLocation(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:ovfToolLocation")
}

// ESXi Password config
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:password")
}

// ESXi Host SSH Port config
func GetSshPort(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "esxi-native:sshPort")
	if err == nil {
		return v
	}
	return "22"
}

// ESXi Host SSL Port config
func GetSslPort(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "esxi-native:sslPort")
	if err == nil {
		return v
	}
	return "443"
}

// ESXi Username config
func GetUsername(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "esxi-native:username")
	if err == nil {
		return v
	}
	return "root"
}
