// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// ESXi Host Name config
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:host")
}

// ESXi Password config
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:password")
}

// ESXi Host SSH Port config
func GetSshPort(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:sshPort")
}

// ESXi Host SSL Port config
func GetSslPort(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:sslPort")
}

// ESXi Username config
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "esxi-native:username")
}
