// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("esxi-native");

/**
 * ESXi Host Name config
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * ESXi Datastore Name config were ovftool will be configured
 */
export declare const ovfToolLocation: string | undefined;
Object.defineProperty(exports, "ovfToolLocation", {
    get() {
        return __config.get("ovfToolLocation");
    },
    enumerable: true,
});

/**
 * ESXi Password config
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * ESXi Host SSH Port config
 */
export declare const sshPort: string;
Object.defineProperty(exports, "sshPort", {
    get() {
        return __config.get("sshPort") ?? "22";
    },
    enumerable: true,
});

/**
 * ESXi Host SSL Port config
 */
export declare const sslPort: string;
Object.defineProperty(exports, "sslPort", {
    get() {
        return __config.get("sslPort") ?? "443";
    },
    enumerable: true,
});

/**
 * ESXi Username config
 */
export declare const username: string;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username") ?? "root";
    },
    enumerable: true,
});

