// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.EsxiNative.Outputs
{

    [OutputType]
    public sealed class NetworkInterface
    {
        public readonly string? MacAddress;
        public readonly string? NicType;
        public readonly string VirtualNetwork;

        [OutputConstructor]
        private NetworkInterface(
            string? macAddress,

            string? nicType,

            string virtualNetwork)
        {
            MacAddress = macAddress;
            NicType = nicType;
            VirtualNetwork = virtualNetwork;
        }
    }
}
