// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EsxiNative.Outputs
{

    [OutputType]
    public sealed class Uplink
    {
        /// <summary>
        /// Uplink name.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private Uplink(string name)
        {
            Name = name;
        }
    }
}
