// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EsxiNative.Outputs
{

    [OutputType]
    public sealed class VirtualDisk
    {
        /// <summary>
        /// SCSI_Ctrl:SCSI_id.    Range  '0:1' to '0:15'.   SCSI_id 7 is not allowed.
        /// </summary>
        public readonly string? Slot;
        public readonly string? VirtualDiskId;

        [OutputConstructor]
        private VirtualDisk(
            string? slot,

            string? virtualDiskId)
        {
            Slot = slot;
            VirtualDiskId = virtualDiskId;
        }
    }
}
