# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .get_virtual_machine import *
from .provider import *
from .virtual_machine import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_esxi_native.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_esxi_native.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "esxi-native",
  "mod": "index",
  "fqn": "pulumi_esxi_native",
  "classes": {
   "esxi-native:index:VirtualMachine": "VirtualMachine"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "esxi-native",
  "token": "pulumi:providers:esxi-native",
  "fqn": "pulumi_esxi_native",
  "class": "Provider"
 }
]
"""
)
