// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface KeyValuePair {
    key: string;
    value: string;
}

export interface NetworkInterface {
    macAddress?: string;
    nicType?: string;
    virtualNetwork?: string;
}

export interface Uplink {
    /**
     * Uplink name.
     */
    name: string;
}

export interface VMVirtualDisk {
    /**
     * SCSI_Ctrl:SCSI_id.    Range  '0:1' to '0:15'.   SCSI_id 7 is not allowed.
     */
    slot?: string;
    virtualDiskId: string;
}

