// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.EsxiNative.Inputs
{

    public sealed class NetworkInterfaceArgs : Pulumi.ResourceArgs
    {
        [Input("macAddress")]
        public Input<string>? MacAddress { get; set; }

        [Input("nicType")]
        public Input<string>? NicType { get; set; }

        [Input("virtualNetwork")]
        public Input<string>? VirtualNetwork { get; set; }

        public NetworkInterfaceArgs()
        {
        }
    }
}
