// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getVirtualMachine";
export * from "./provider";
export * from "./resourcePool";
export * from "./virtualDisk";
export * from "./virtualMachine";
export * from "./virtualSwitch";

// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

// Import resources to register:
import { ResourcePool } from "./resourcePool";
import { VirtualDisk } from "./virtualDisk";
import { VirtualMachine } from "./virtualMachine";
import { VirtualSwitch } from "./virtualSwitch";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "esxi-native:index:ResourcePool":
                return new ResourcePool(name, <any>undefined, { urn })
            case "esxi-native:index:VirtualDisk":
                return new VirtualDisk(name, <any>undefined, { urn })
            case "esxi-native:index:VirtualMachine":
                return new VirtualMachine(name, <any>undefined, { urn })
            case "esxi-native:index:VirtualSwitch":
                return new VirtualSwitch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("esxi-native", "index", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("esxi-native", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:esxi-native") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
