// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PortGroup extends pulumi.CustomResource {
    /**
     * Get an existing PortGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortGroup {
        return new PortGroup(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'esxi-native:index:PortGroup';

    /**
     * Returns true if the given object is an instance of PortGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortGroup.__pulumiType;
    }

    /**
     * Forged transmits (true=Accept/false=Reject).
     */
    public readonly forgedTransmits!: pulumi.Output<boolean | undefined>;
    /**
     * MAC address changes (true=Accept/false=Reject).
     */
    public readonly macChanges!: pulumi.Output<boolean | undefined>;
    /**
     * Port Group name.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Promiscuous mode (true=Accept/false=Reject).
     */
    public readonly promiscuousMode!: pulumi.Output<boolean | undefined>;
    /**
     * Virtual Switch Name.
     */
    public readonly vSwitch!: pulumi.Output<string>;
    /**
     * Port Group vlan id
     */
    public readonly vlan!: pulumi.Output<number>;

    /**
     * Create a PortGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PortGroupArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.vSwitch === undefined) && !opts.urn) {
                throw new Error("Missing required property 'vSwitch'");
            }
            resourceInputs["forgedTransmits"] = args ? args.forgedTransmits : undefined;
            resourceInputs["macChanges"] = args ? args.macChanges : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["promiscuousMode"] = args ? args.promiscuousMode : undefined;
            resourceInputs["vSwitch"] = args ? args.vSwitch : undefined;
            resourceInputs["vlan"] = args ? args.vlan : undefined;
        } else {
            resourceInputs["forgedTransmits"] = undefined /*out*/;
            resourceInputs["macChanges"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["promiscuousMode"] = undefined /*out*/;
            resourceInputs["vSwitch"] = undefined /*out*/;
            resourceInputs["vlan"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PortGroup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortGroup resource.
 */
export interface PortGroupArgs {
    /**
     * Forged transmits (true=Accept/false=Reject).
     */
    forgedTransmits?: pulumi.Input<boolean>;
    /**
     * MAC address changes (true=Accept/false=Reject).
     */
    macChanges?: pulumi.Input<boolean>;
    /**
     * Virtual Switch name.
     */
    name?: pulumi.Input<string>;
    /**
     * Promiscuous mode (true=Accept/false=Reject).
     */
    promiscuousMode?: pulumi.Input<boolean>;
    /**
     * Virtual Switch Name.
     */
    vSwitch: pulumi.Input<string>;
    /**
     * Port Group vlan id
     */
    vlan?: pulumi.Input<number>;
}
